esphome:
  name: lockbox1
  friendly_name: lockbox1

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "vwXl6o5sdH1zOhIU4Uw4nDsvUTq7tHuC+WgmjfbhjUE="

ota:
  - platform: esphome
    password: "fe77b8f7b105e6d85bbd164db9c0d364"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lockbox1 Fallback Hotspot"
    password: "RKqRNja4Prw7"

captive_portal:
    